export PATH=/usr/local/bin:$PATH:/usr/local/share/npm/bin:/usr/bin:/bin:/usr/sbin:/usr/local/sbin:/sbin:

# export TERM=screen-256color
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=/Users/ilian/workspace
source /usr/local/bin/virtualenvwrapper.sh


# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/ilian/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/ilian/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/ilian/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/ilian/Downloads/google-cloud-sdk/completion.zsh.inc'
fi


# RVM stuff
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*


# MacPorts Installer addition on 2016-01-02_at_12:48:54: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# Golang stuff
export GOPATH=$HOME/workspace
export PATH="$PATH:$HOME/.rvm/bin:$GOPATH/bin" # Add RVM to PATH for scripting
