export ZSH=/Users/ilian/.oh-my-zsh

ZSH_THEME="my-theme"

plugins=(git wd zsh-syntax-highlighting nvm)

source $ZSH/oh-my-zsh.sh

eval "$(direnv hook zsh)"


# Needed for openssl
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

export NVM_DIR=~/.nvm

# Golang stuff
export GOPATH=$HOME/workspace
export PATH="$PATH:$HOME/.rvm/bin:$GOPATH/bin" # Add RVM to PATH for scripting
export GOPRIVATE=github.com/lifesum/*

# virtualenvwrapper settings
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /Users/ilian/Library/Python/3.8/bin/virtualenvwrapper.sh


[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Mapping the CapsLock to Play/Pause button so I can use it with an external keyboard
hidutil property --set '{"UserKeyMapping":[{"HIDKeyboardModifierMappingSrc":0x000700000039, "HIDKeyboardModifierMappingDst":0x000C000000CD}]}'

# Localstack alias
# default region should be us-east-1
alias awslocal="AWS_ACCESS_KEY_ID=XXX AWS_SECRET_ACCESS_KEY=XXX AWS_DEFAULT_REGION=${DEFAULT_REGION:-$AWS_DEFAULT_REGION} aws --endpoint-url=http://${LOCALSTACK_HOST:-localhost}:4566"


# GPG commits signing
export GPG_TTY=$(tty)
git config --global gpg.program gpg
git config --global commit.gpgsign true